# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship_profile', '0002_auto_20180113_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=40)),
                ('request_message', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing', to='mentorship_profile.Mentee')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing', to='mentorship_profile.Mentor')),
            ],
        ),
    ]
