# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('unapproved', 'Unapproved')], default='unapproved', max_length=30)),
                ('category', models.CharField(choices=[('data science', 'Data Science'), ('backend devops', 'Back End / DevOps'), ('web full stack', 'Web / Full Stack Development'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('slack_handle', models.CharField(blank=True, max_length=40, null=True)),
                ('linked_in_url', models.URLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('goals', models.TextField()),
                ('currently_accepting_mentees', models.BooleanField(default=False)),
                ('mentee_capacity', models.IntegerField(default=5)),
                ('mentees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_by', to=settings.AUTH_USER_MODEL)),
                ('mentors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
