# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0004_profile_years_industry_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_industry_experience',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1 - 2'), ('3-7', '3 - 7'), ('7+', '7 +')], default='0', max_length=3),
        ),
    ]
