# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0004_auto_20180821_2024'),
        ('mentorship_profile', '0007_auto_20180815_0337'),
    ]

    operations = [
    ]
