# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0005_auto_20180822_1708'),
        ('mentorship_profile', '0008_merge_20180822_0303'),
    ]

    operations = [
    ]
