# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0009_merge_20180822_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_industry_experience',
            field=models.CharField(choices=[('0-1', '0 - 1'), ('1-3', '1 - 3'), ('3-7', '3 - 7'), ('7+', '7 +')], default='0-1', max_length=3),
        ),
    ]
